### ISSUE TITLE
tabBar中选中的icon路径中图片名与实际不一致，注意区分大小写哈

### ISSUE THREAD

**Issue by haohao594** [iDestin/Himalayan-lite#4]
修改了一下icon路径之后就可以预览了，有个成型的框架，最近要写个小程序，谢啦，给你个star

**Comment by iDestin** [comment]
> 修改了一下icon路径之后就可以预览了，有个成型的框架，最近要写个小程序，谢啦，给你个star

....哈哈！谢谢提醒，这个小程序的代码可能还比较简陋😂，使用的话建议还要打磨一下
