### ISSUE TITLE
编译后发现模拟器上除了菜单栏没有显示内容

### ISSUE THREAD

**Issue by SSFsystem** [iDestin/Himalayan-lite#8]
编译后发现模拟器上除了菜单栏没有显示内容,猜测是不是api变动的问题

**Comment by iDestin** [comment]
我测试之后的确出现了以上情况，但是当我再次编译之后问题消失了，应该是api的问题，因为这个api也不是官方api所以可能会出现一些问题

**Comment by iDestin** [comment]
你可以尝试多编译几次

**Comment by SSFsystem** [comment]
非常感谢你的帮助,问题确实解决了
